version : "3"  
services:
  react-app-frontend: #frontend image build
    image: "frontend"
    stdin_open: true  #keeps container open for communication
    ports: "3000:3000"    
  backend:            #backend image build
    image: "backend"
    ports: "5000:5000"
    depends_on: db
  db:
    image: "db"   #db image
    ports: 80:80
